name: Docker Image Build/Push to Amazon ECR

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build-ecr-push:
    name: Docker Image Build/Push to Amazon ECR
    uses: wibaek/github-automation/.github/workflows/docker-build-ecr-push.yaml@v1.0
    with:
      aws-region: ${{ vars.AWS_REGION }}
      aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
      image-name: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/my-app"
      context: "."
      dockerfile: "./Dockerfile"
      platforms: "linux/amd64"
      tags: |
        type=raw,value=${{ github.sha }}
      cache-type: "gha"
      cache-scope: "my-app"
