name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    uses: wibaek/gha/.github/workflows/release.yaml@v1.0
    with:
      # release-please release type입니다.
      # 선택 예: simple, node, python
      release-type: "simple"
